version: '3'

services:
  postgres:
    container_name: composepostgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: daee
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "daee", "-U", "postgres"]
      interval: 5s
      retries: 5

  web:
    build: .
    ports:
      - "2999:8081"
    depends_on:
      - postgres

volumes:
  pgdata:

  #TODO: fix it