version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: daee
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    image: frontend
    build: webdaee/
    ports:
      - "3000:3000"

volumes:
  pgdata:

  #TODO: fix it