// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: proto/daee.proto

package daee

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщения для описания запроса на доступность агента
type AvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AvRequest) Reset() {
	*x = AvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daee_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvRequest) ProtoMessage() {}

func (x *AvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daee_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvRequest.ProtoReflect.Descriptor instead.
func (*AvRequest) Descriptor() ([]byte, []int) {
	return file_proto_daee_proto_rawDescGZIP(), []int{0}
}

// Сообщение для описания результата доступности агента(да/нет)
type AvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AvResponse) Reset() {
	*x = AvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daee_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvResponse) ProtoMessage() {}

func (x *AvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daee_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvResponse.ProtoReflect.Descriptor instead.
func (*AvResponse) Descriptor() ([]byte, []int) {
	return file_proto_daee_proto_rawDescGZIP(), []int{1}
}

func (x *AvResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

// Сообщение для описания запроса на вычисление выражения
type OpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A        float32 `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B        float32 `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
	Operator string  `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Time     int64   `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *OpRequest) Reset() {
	*x = OpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daee_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRequest) ProtoMessage() {}

func (x *OpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daee_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRequest.ProtoReflect.Descriptor instead.
func (*OpRequest) Descriptor() ([]byte, []int) {
	return file_proto_daee_proto_rawDescGZIP(), []int{2}
}

func (x *OpRequest) GetA() float32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *OpRequest) GetB() float32 {
	if x != nil {
		return x.B
	}
	return 0
}

func (x *OpRequest) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

func (x *OpRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// Сообщение для описания результата вычисления выражения
type OpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result float32 `protobuf:"fixed32,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *OpResponse) Reset() {
	*x = OpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_daee_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResponse) ProtoMessage() {}

func (x *OpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_daee_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResponse.ProtoReflect.Descriptor instead.
func (*OpResponse) Descriptor() ([]byte, []int) {
	return file_proto_daee_proto_rawDescGZIP(), []int{3}
}

func (x *OpResponse) GetResult() float32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_proto_daee_proto protoreflect.FileDescriptor

var file_proto_daee_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x65, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x0b, 0x0a, 0x09, 0x41, 0x76, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x0a, 0x41, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x57, 0x0a, 0x09, 0x4f, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x62, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x0a, 0x4f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x5c, 0x0a, 0x0c, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x02, 0x41, 0x76, 0x12,
	0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x02, 0x4f, 0x70, 0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x70, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4f, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a, 0x17, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x6e, 0x64, 0x69, 0x7a, 0x69, 0x2f, 0x64, 0x61,
	0x65, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_daee_proto_rawDescOnce sync.Once
	file_proto_daee_proto_rawDescData = file_proto_daee_proto_rawDesc
)

func file_proto_daee_proto_rawDescGZIP() []byte {
	file_proto_daee_proto_rawDescOnce.Do(func() {
		file_proto_daee_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_daee_proto_rawDescData)
	})
	return file_proto_daee_proto_rawDescData
}

var file_proto_daee_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_daee_proto_goTypes = []interface{}{
	(*AvRequest)(nil),  // 0: api.AvRequest
	(*AvResponse)(nil), // 1: api.AvResponse
	(*OpRequest)(nil),  // 2: api.OpRequest
	(*OpResponse)(nil), // 3: api.OpResponse
}
var file_proto_daee_proto_depIdxs = []int32{
	0, // 0: api.AgentService.Av:input_type -> api.AvRequest
	2, // 1: api.AgentService.Op:input_type -> api.OpRequest
	1, // 2: api.AgentService.Av:output_type -> api.AvResponse
	3, // 3: api.AgentService.Op:output_type -> api.OpResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_daee_proto_init() }
func file_proto_daee_proto_init() {
	if File_proto_daee_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_daee_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daee_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daee_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_daee_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_daee_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_daee_proto_goTypes,
		DependencyIndexes: file_proto_daee_proto_depIdxs,
		MessageInfos:      file_proto_daee_proto_msgTypes,
	}.Build()
	File_proto_daee_proto = out.File
	file_proto_daee_proto_rawDesc = nil
	file_proto_daee_proto_goTypes = nil
	file_proto_daee_proto_depIdxs = nil
}
